---
title: "Tracker structure"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M %Z', tz = 'America/Los_Angeles')`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
params:
  workers: 14
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.width = 11, fig.height = 5, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = here::here())
ggplot2::theme_set(ggplot2::theme_bw() + ggplot2::theme(panel.grid.minor = ggplot2::element_blank()))
suppressPackageStartupMessages(source(here::here("R/load_all.R")))
```

What shape should the offset have? All four sections calibrate the submitted flu ensemble: the working scale (E03), the leak and the slow term (E04), the warm start from the burn-in season (E05), and a constant against an adaptive learning rate (E11). Each section is a self-contained experiment with its own runs;
the ids match `notes/calibration-ledger.md`.

```{r e03, results="asis"}
cal_section("_e03_scale.Rmd", list(workers = params$workers))
```

```{r e04, results="asis"}
cal_section("_e04_offset_structure.Rmd", list(workers = params$workers))
```

```{r e05, results="asis"}
cal_section("_e05_warm_start.Rmd", list(workers = params$workers))
```

```{r e11, results="asis"}
cal_section("_e11_constant_lr.Rmd", list(workers = params$workers))
```
