# Models

## Our Models: Simplest

::: {.notes}
In order of increasing complexity/usage
:::

- `linear`: linearly extrapolate the last 4 weeks
- `climate_base`: a climatological model, quantiles estimated from a 7 week period centered on the `target_date`'s season week from historical data for that geo
- `climate_geo`: a climatological model, like `climate_base` but converts to rates, and then creates quantiles using all geos.
- `climate_linear`: a weighted ensemble of the climatological and linear
```{r climate_weight_plot, fig.width = 20, fig.height = 3, fig.align = "center"}
weights <-
  make_ahead_weights(-1:3) %>%
  left_join(
    make_quantile_weights(covidhub_probs()),
    by = c("forecast_family"),
    relationship = "many-to-many"
  ) %>%
  mutate(weight = weight.x * weight.y) %>%
  select(forecast_family, quantile, ahead, weight) %>%
  mutate(ahead = factor(ahead), quantile = factor(quantile))
weights %>%
  filter(forecast_family == "climate") %>%
  ggplot(aes(y = ahead, x = quantile, fill = weight)) +
  geom_tile() +
  scale_fill_viridis_c(limits = c(0,1))
```

## Our Models: Autoregressive

- `windowed_seasonal`: an AR model where the training data is taken from a window 4 weeks before and after the training
  + The model is roughly $x_t = x_{t-7} + x_{t-14}$, where $x$ is the scaled NHSN data (along with ILI+ and FluSURV) and $t$ is the target date in days.
  + Covid predicted this on rates data
  + For flu, this model also uses ILI+ data and fluSURV, with the forecasts done on variance-stabilized, scaled, and centered data, on a per-geo-source basis.
    - the variance stabilization is a 4th root
    - the scaling is by the difference between the 5th and 95th quantiles
    - the centering is so that the median is zero

::: {.notes}
This "training window" approach to handling seasonality gave a large improvement to the model score over the base AR model.
The augmented data sources also improved the model score.
We did not see much improvement from adding more lags or tweaking the whitening settings.
:::

## Our Models: Autoregressive with Exogenous Predictors

- `windowed_seasonal_nssp`: like `windowed_seasonal` without the data scaling, and using `nssp` (emergency department visits) as an exogenous predictor (same lags).
  + The model is roughly $x_t = x_{t-7} + x_{t-14} + y_{t-7} + y_{t-14}$, where $x$ is the scaled NHSN data (along with ILI+ and FluSURV) and $y$ is the NSSP data, and $t$ is the target date in days.

::: {.notes}
This exogenous predictor gave the largest improvement to the model score out of Google Symptoms and NWSS.
:::

## Timeline of models used {.smaller}
:::: {.columns}
::: {.column width = "50%"}
### Flu Model {.smaller}
- `2024-11-21` initial forecast, straight average of `climate_base`, `climate_geo` and `linear`
- `2024-11-27` `climate_linear` ensemble instead of average (2 weeks)
- `2024-12-11` introduce `windowed_seasonal` to ensemble (5 weeks)
- `2025-01-15` introduce `windowed_seasonal_nssp` to ensemble
- Final model ensembles `windowed_seasonal` (which uses ILI+ and FluSURV), `windowed_seasonal_nssp` (which doesn't), and `climate_linear`
:::

::: {.column width = "50%"}
### Covid Model {.smaller}
- `2024-11-21` initial forecast, straight average of `climate_base`, `climate_geo` and `linear`
- `2024-11-27` `climate_linear` ensemble instead of average (9 weeks)
- `2025-01-29` `windowed_seasonal_nssp` introduced to ensemble
- `2025-02-19` forecast using only `windowed_seasonal_nssp`
- Final model uses only `windowed_seasonal_nssp`, except for states without `nssp`, where it ensembles `windowed_seasonal` and `climate_linear`
:::

::::

::: {.notes}
The takeaway here is mostly that we changed the model a lot as the season progressed.
:::
