suppressPackageStartupMessages(source(here::here("R", "load_all.R")))

# Oracle tests for the MultiQT port in R/calibration/qt.R.
#
# The fixtures in fixtures/qt/ are the output of `utils.py::projectedQT` on the
# `delphi-fixes` branch of ~/repos/delphi/multiQT (the authors' code plus the
# bugfixes reported upstream), generated by multiQT/make_r_fixtures.py with
# `lr_window = 50` -- the same default the R side uses. Regenerate with:
#   cd ~/repos/delphi/multiQT   # on delphi-fixes
#   uv run --with numpy --with scikit-learn --with matplotlib python make_r_fixtures.py
#   cp r_fixtures/*.csv <this repo>/tests/testthat/fixtures/qt/

QT_FIXTURE_DIR <- test_path("fixtures", "qt")

qt_read_fixture <- function(name) {
  rd <- function(suffix) {
    readr::read_csv(
      file.path(QT_FIXTURE_DIR, glue::glue("{name}_{suffix}.csv")),
      show_col_types = FALSE, progress = FALSE
    )
  }
  Y <- rd("Y")$Y
  levels <- rd("levels")$level
  as_mat <- function(df) unname(as.matrix(df))
  delay_tbl <- rd("delay")
  n <- length(Y)
  # An empty delay file means the fixture used Python's `delay=None`, i.e. no
  # delay at all -- distinct from "a delay in which nothing is ever revealed".
  delay <- if (nrow(delay_tbl) == 0L) {
    NULL
  } else {
    out <- rep(list(integer(0)), n)
    for (t in unique(delay_tbl$round)) {
      out[[t]] <- as.integer(delay_tbl$revealed[delay_tbl$round == t])
    }
    out
  }
  list(Y = Y, Yhat = as_mat(rd("Yhat")), levels = levels,
       played = as_mat(rd("played")), delay = delay)
}

qt_fixture_index <- readr::read_csv(
  file.path(QT_FIXTURE_DIR, "index.csv"), show_col_types = FALSE, progress = FALSE
)

test_that("the fixture set covers the configurations we care about", {
  expect_gt(nrow(qt_fixture_index), 0)
  expect_setequal(qt_fixture_index$projection, c("isotonic", "sort", "none"))
  expect_true(any(qt_fixture_index$lr == "adaptive+"))
  expect_true(any(qt_fixture_index$lr != "adaptive+")) # a constant-lr case
  expect_true(any(qt_fixture_index$has_delay == 0L))
  expect_true(any(qt_fixture_index$has_delay == 1L))
  expect_true(any(qt_fixture_index$m == 23L)) # the hub's level set
})

# --- The load-bearing test -------------------------------------------------
# One test_that per fixture so a failure names the configuration that broke.
for (.i in seq_len(nrow(qt_fixture_index))) {
  local({
    row <- qt_fixture_index[.i, ]
    name <- row$name
    test_that(glue::glue("qt_track reproduces projectedQT exactly: {name}"), {
      fx <- qt_read_fixture(name)
      lr <- if (row$lr == "adaptive+") "adaptive+" else as.numeric(row$lr)
      res <- qt_track(
        Y = fx$Y, Yhat = fx$Yhat, levels = fx$levels, delay = fx$delay,
        lr = lr,
        lr_window = 50, # what make_r_fixtures.py passes
        projection = row$projection,
        eval_grad_at = "played"
      )
      expect_equal(dim(res$played), dim(fx$played))
      expect_equal(res$played, fx$played, tolerance = 1e-10)
    })
  })
}

test_that("round 1 plays the projected base forecast", {
  fx <- qt_read_fixture("hub_delay2")
  res <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay)
  expect_equal(res$played[, 1], stats::isoreg(fx$Yhat[, 1])$yf)
})


# --- Delay construction ----------------------------------------------------

test_that("qt_delay_from_dates puts d = h + 2 rounds of lag on hub coordinates", {
  # FluSight: reference_date and target_end_date are both Saturdays, with
  # target_end_date = reference_date + 7 * horizon. Two weeks of settling then
  # gives exactly h + 2 rounds of delay -- no ceiling, unlike our internal
  # Wednesday convention.
  rounds <- seq(as.Date("2025-01-04"), by = 7, length.out = 20)
  for (h in -1:3) {
    delay <- qt_delay_from_dates(rounds, rounds + 7 * h, settle_days = 14L)
    revealed_at <- rep(NA_integer_, length(rounds))
    for (t in seq_along(delay)) revealed_at[delay[[t]]] <- t
    lag <- revealed_at - seq_along(rounds)
    expect_equal(unique(stats::na.omit(lag)), h + 2L, info = glue::glue("h = {h}"))
  }
})

test_that("qt_delay_from_dates makes calendar gaps cost extra staleness", {
  # A missing round means the outcome waits for the next one that exists, so the
  # realised lag in rounds is smaller but the offset applied is calendar-staler.
  rounds <- as.Date(c(
    "2025-01-04", "2025-01-11", "2025-01-18",
    # 2025-01-25 skipped
    "2025-02-01", "2025-02-08"
  ))
  delay <- qt_delay_from_dates(rounds, rounds + 7L, settle_days = 14L)
  # Round 1 targets 2025-01-11, trustworthy 2025-01-25, which is not a round;
  # it is therefore first learnable at 2025-02-01 = round 4, a 3-round lag
  # rather than the nominal 3 weeks (h + 2 = 3 would have been round 4 anyway
  # here) -- the invariant that matters is that nothing is revealed early.
  expect_true(all(vapply(seq_along(delay), function(t) all(delay[[t]] <= t), logical(1))))
  expect_equal(sum(lengths(delay)), sum(rounds + 7L + 14L <= max(rounds)))
})

test_that("qt_delay_from_dates reveals every outcome at most once", {
  rounds <- seq(as.Date("2025-01-04"), by = 7, length.out = 40)
  delay <- qt_delay_from_dates(rounds, rounds + 21L)
  flat <- unlist(delay)
  expect_false(any(duplicated(flat)))
})

test_that("delay validation rejects future reveals and double reveals", {
  Y <- runif(5, 1, 10)
  Yhat <- matrix(5, nrow = 2, ncol = 5)
  levels <- c(0.25, 0.75)
  future <- list(integer(0), 5L, integer(0), integer(0), integer(0))
  expect_error(qt_track(Y, Yhat, levels, future), "future outcome")
  twice <- list(1L, 1L, integer(0), integer(0), integer(0))
  expect_error(qt_track(Y, Yhat, levels, twice), "more than once")
})

test_that("qt_track refuses to learn from an NA outcome", {
  Y <- c(1, NA, 3, 4, 5)
  Yhat <- matrix(2, nrow = 2, ncol = 5)
  levels <- c(0.25, 0.75)
  expect_error(qt_track(Y, Yhat, levels), "reveals round 2 whose")
  # ... but an NA in a round that is never revealed is fine, which is how the
  # tail of a live season behaves.
  never <- list(integer(0), integer(0), 1L, 3L, 4L)
  expect_no_error(qt_track(Y, Yhat, levels, never))
})


# --- Properties the method must have ---------------------------------------

test_that("isotonic projection yields non-crossing quantiles, 'none' does not", {
  fx <- qt_read_fixture("hub_none")
  iso <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, projection = "isotonic")
  raw <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, projection = "none")
  expect_true(all(apply(iso$played, 2, function(col) all(diff(col) >= -1e-9))))
  # The point of MultiQT: plain QT does cross on this data, so the projection is
  # doing real work rather than being a no-op we could drop.
  expect_true(any(apply(raw$played, 2, function(col) any(diff(col) < -1e-9))))
})

test_that("sort and isotonic are both monotone but are not the same projection", {
  fx <- qt_read_fixture("hub_delay2")
  iso <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, projection = "isotonic")
  srt <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, projection = "sort")
  expect_true(all(apply(srt$played, 2, function(col) all(diff(col) >= -1e-9))))
  expect_false(isTRUE(all.equal(iso$played, srt$played)))
})

test_that("calibration improves coverage over the miscalibrated base forecasts", {
  fx <- qt_read_fixture("hub_delay2")
  res <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay)
  cov_of <- function(q) rowMeans(fx$Y[col(q)] <= q)
  gap <- function(q) mean(abs(cov_of(q) - fx$levels))
  # The fixtures' base forecasts are deliberately biased and too narrow.
  expect_lt(gap(res$played), gap(fx$Yhat))
})

test_that("the tracker is equivariant under rescaling, up to the lr floor", {
  fx <- qt_read_fixture("hub_delay2")
  c_ <- 1000
  a <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay)
  b <- qt_track(fx$Y * c_, fx$Yhat * c_, fx$levels, fx$delay)
  # Scale up so the 0.1 floor cannot bind in either run, then equivariance is exact.
  expect_equal(b$played, a$played * c_, tolerance = 1e-8)
})

test_that("lr_window actually windows over time", {
  # Shrinking the window must change the learning-rate trajectory, and Inf must
  # equal a window longer than the series.
  fx <- qt_read_fixture("hub_delay2")
  short <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, lr_window = 8)
  long <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, lr_window = 1e6)
  inf_ <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, lr_window = Inf)
  expect_equal(long$lr, inf_$lr)
  expect_false(isTRUE(all.equal(short$lr, long$lr)))
  # An expanding window can only ever grow its residual pool, so its lr is
  # non-decreasing in the pool; a short window is free to come back down.
  expect_gt(stats::sd(short$lr[short$lr > 0]), 0)
})

test_that("the adaptive lr is the 90th percentile of |Y - Yhat|, pooled over levels", {
  # Regression guard for a real porting bug: numpy broadcasts `Y - Yhat` along
  # the last axis, R recycles a vector column-major *down* the matrix. Getting
  # that wrong transposes the outcome onto the level axis and silently corrupts
  # every learning rate, while leaving the algorithm's shape intact. Pinning eta
  # against a hand-rolled residual matrix is the cheapest way to catch it.
  fx <- qt_read_fixture("small_nodelay")
  m <- length(fx$levels)
  n <- length(fx$Y)
  resid <- abs(matrix(fx$Y, nrow = m, ncol = n, byrow = TRUE) - fx$Yhat)
  res <- qt_track(fx$Y, fx$Yhat, fx$levels, lr_window = Inf)
  # Round t updates from the residuals observed through t; with no delay that is
  # columns 1:t.
  for (t in c(1L, 5L, 20L, n - 1L)) {
    expected <- max(0.1, 0.1 * stats::quantile(
      resid[, seq_len(t)], 0.9, names = FALSE, type = 7L
    ))
    expect_equal(res$lr[t], expected, info = glue::glue("round {t}"))
  }
  # A finite window really drops old columns.
  res8 <- qt_track(fx$Y, fx$Yhat, fx$levels, lr_window = 8)
  t <- 30L
  expect_equal(res8$lr[t], max(0.1, 0.1 * stats::quantile(
    resid[, (t - 7L):t], 0.9, names = FALSE, type = 7L
  )))
})

test_that("a constant lr is used verbatim and an invalid lr is rejected", {
  fx <- qt_read_fixture("small_nodelay")
  res <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, lr = 3)
  expect_true(all(res$lr[res$lr > 0] == 3))
  expect_error(qt_track(fx$Y, fx$Yhat, fx$levels, lr = -1), "positive")
  expect_error(qt_track(fx$Y, fx$Yhat, fx$levels, lr = "adaptive++"), "adaptive\\+")
})

test_that("qt_track validates shapes and level ordering", {
  Y <- runif(6, 1, 10)
  ok <- matrix(5, nrow = 3, ncol = 6)
  lv <- c(0.1, 0.5, 0.9)
  expect_error(qt_track(Y, matrix(5, 2, 6), lv), "must be 3 x 6")
  expect_error(qt_track(Y, ok, c(0.5, 0.1, 0.9)), "strictly increasing")
  expect_error(qt_track(Y, ok, c(0, 0.5, 0.9)), "strictly inside")
  expect_error(qt_track(Y, ok, lv, lr_window = 0), "lr_window")
})

# --- Ragged rounds, burn-in and the season gap ------------------------------

test_that("inactive rounds carry the offsets without playing or scoring", {
  fx <- qt_read_fixture("hub_delay2")
  n <- length(fx$Y)
  gone <- c(20L, 21L, 47L)
  Yhat <- fx$Yhat
  Yhat[, gone] <- NA_real_
  delay <- lapply(fx$delay, function(i) setdiff(i, gone))
  res <- qt_track(fx$Y, Yhat, fx$levels, delay)
  # Nothing is played where there was no base forecast ...
  expect_true(all(is.na(res$played[, gone])))
  # ... and everything else is played.
  expect_false(anyNA(res$played[, -gone]))
  # The offset state survives the hole intact -- no NA, no reset.
  expect_false(anyNA(res$hidden))
  expect_true(any(res$hidden[, max(gone)] != 0))
  # With a 2-round delay, rounds 22 and 23 would have revealed the outcomes of
  # the (unplayed) rounds 20 and 21, so they now reveal nothing and the offsets
  # are simply held.
  expect_equal(lengths(delay[22:23]), c(0L, 0L))
  expect_equal(res$hidden[, 23L], res$hidden[, 22L])
  expect_equal(res$hidden[, 24L], res$hidden[, 23L])
})

test_that("a half-missing round is an error, not silently padded", {
  fx <- qt_read_fixture("hub_delay2")
  Yhat <- fx$Yhat
  Yhat[1:5, 30L] <- NA_real_
  expect_error(qt_track(fx$Y, Yhat, fx$levels, fx$delay), "partially missing")
})

test_that("delay may not reveal a round that was never played", {
  fx <- qt_read_fixture("hub_delay2")
  Yhat <- fx$Yhat
  Yhat[, 20L] <- NA_real_
  # fx$delay still reveals round 20 somewhere.
  expect_error(qt_track(fx$Y, Yhat, fx$levels, fx$delay), "no base forecast")
})

test_that("update_from suppresses steps but still warms up the learning rate", {
  fx <- qt_read_fixture("hub_delay2")
  n <- length(fx$Y)
  burn <- seq_len(30L)
  res <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay,
    update_from = !(seq_len(n) %in% burn)
  )
  full <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay)
  # Offsets stay at zero through burn-in, so the played value is the base.
  expect_true(all(res$hidden[, burn] == 0))
  expected <- apply(fx$Yhat[, burn], 2, function(v) stats::isoreg(v)$yf)
  expect_equal(res$played[, burn], expected, tolerance = 1e-9)
  # eta is still recorded during burn-in -- that is the point of a burn-in.
  expect_true(all(res$lr[burn][lengths(fx$delay[burn]) > 0] > 0))
  expect_equal(res$lr, full$lr)
  # And it does something afterwards.
  expect_true(any(res$hidden[, n] != 0))
})

test_that("hidden_scale expresses the season-gap policy", {
  fx <- qt_read_fixture("hub_delay2")
  n <- length(fx$Y)
  boundary <- 45L
  carry <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay)
  reset <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay,
    hidden_scale = replace(rep(1, n), boundary, 0)
  )
  shrink <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay,
    hidden_scale = replace(rep(1, n), boundary, 0.5)
  )
  expect_true(all(reset$hidden[, boundary] == 0))
  expect_equal(shrink$hidden[, boundary], 0.5 * carry$hidden[, boundary])
  # Before the boundary all three are identical.
  expect_equal(carry$hidden[, seq_len(boundary - 1L)], reset$hidden[, seq_len(boundary - 1L)])
})


test_that("offset and played are consistent, and nonneg clamps after projection", {
  fx <- qt_read_fixture("hub_delay2")
  res <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay)
  expect_equal(res$offset, res$played - fx$Yhat)
  clamped <- qt_track(fx$Y, fx$Yhat, fx$levels, fx$delay, nonneg = TRUE)
  expect_true(all(clamped$played >= 0))
  # Clamping must not feed back into the learning path.
  expect_equal(clamped$hidden, res$hidden)
  expect_equal(clamped$lr, res$lr)
})
