# veteran_state_df.csv and veteran_pop.csv are generated by process_va_data.py
# and uploaded to the forecasting-team-data bucket with
# s3write_using(
#   read_csv("va_explore/veteran_state_df.csv"),
#   FUN = write_csv,
#   bucket = "forecasting-team-data",
#   object = "va_explore/veteran_state_df.csv"
# )
# and
# s3write_using(
#   read_csv("va_explore/veteran_pop.csv"),
#   FUN = write_csv,
#   bucket = "forecasting-team-data",
#   object = "va_explore/veteran_pop.csv"
# )

library(aws.s3)
library(epidatr)
library(tidyverse)
options(readr.show_progress = FALSE)
options(readr.show_col_types = FALSE)

vdf <- s3read_using(read_csv, bucket = "forecasting-team-data", object = "va_explore/veteran_state_df.csv") %>%
  left_join(
    s3read_using(read_csv, bucket = "forecasting-team-data", object = "va_explore/veteran_pop.csv"),
    by = "state"
  ) %>%
  mutate(across(starts_with("unique_patients"), ~ . * 1e5 / veteran_population)) %>%
  rename_with(~ paste0(., "_per_100k"), starts_with("unique_patients")) %>%
  select(-veteran_population)
hdf <- pub_covidcast(
  source = "hhs",
  signals = "confirmed_admissions_influenza_1d_prop",
  geo_type = "state",
  geo_values = "*",
  time_type = "day"
) %>%
  select(geo_value, time_value, value) %>%
  rename(state = geo_value, date = time_value, admissions_prop = value)
df <- vdf %>%
  left_join(hdf, by = c("state", "date")) %>%
  filter(date >= as.Date("2020-10-01"))

geo_filter <- c("fl", "tx", "ca")

# 2021
df %>%
  filter(state %in% geo_filter) %>%
  filter(date >= as.Date("2021-01-01") & date <= as.Date("2021-12-31")) %>%
  ggplot(aes(x = date, y = admissions_prop)) +
  geom_line() +
  geom_line(aes(y = unique_patients_flu_per_100k), color = "blue") +
  facet_wrap(~state)

# 2022
df %>%
  filter(state %in% geo_filter) %>%
  filter(date >= as.Date("2022-01-01") & date <= as.Date("2022-12-31")) %>%
  ggplot(aes(x = date, y = admissions_prop)) +
  geom_line() +
  geom_line(aes(y = unique_patients_flu_per_100k), color = "blue") +
  facet_wrap(~state)

# 2023
df %>%
  filter(state %in% geo_filter) %>%
  filter(date >= as.Date("2023-01-01") & date <= as.Date("2023-12-31")) %>%
  ggplot(aes(x = date, y = admissions_prop)) +
  geom_line() +
  geom_line(aes(y = unique_patients_flu_per_100k), color = "blue") +
  facet_wrap(~state)
