# A collection of dependencies for this repo. A mix of dev and non-dev
# dependencies to aid in the creation of a `renv` lockfile. Not all of these are
# needed to run the pipeline, but it's cleaner to have a single file with all
# the dependencies listed.
library(assertthat)
library(aws.s3)
library(cli)
library(crew)
library(data.table)
library(grf)
library(dplyr)
library(epidatr)
library(epipredict)
library(epiprocess)
library(glue)
library(grf)
library(here)
library(jsonlite)
library(languageserver)
library(lubridate)
library(magrittr)
library(pak)
library(parsnip)
library(paws.storage)
library(purrr)
library(quantreg)
library(recipes)
library(renv)
library(rlang)
library(rspm)
library(scoringutils)
library(slider)
library(tarchetypes)
library(targets)
library(testthat)
library(tibble)
library(tidyr)
library(usethis)
library(zeallot)
